apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gazzettataskexcelcron
spec:
    schedule: "*/10 * * * *"
    concurrencyPolicy: Allow
    jobTemplate:
        spec:
            template:
                spec:
                    restartPolicy: Never
                    containers:
                    - name: gazzettataskexcelcron
                      image: efsadsreg.azurecr.io/taskexcelcron